### ISSUE TITLE
MFALambdaInputs error on 'amplify publish'

### ISSUE THREAD

**Issue by martijn-veenstra** [awslabs/aws-amplify-identity-broker#193]
Keep getting this error.... Any thoughts?

CREATE_FAILED authamplifyIdentityBrokerAuth AWS::CloudFormation::Stack Thu Oct 07 2021 17:29:24 GMT+0200 (Midden-Europese zomertijd) Embedded stack arn:aws:cloudformation:eu-west-1:562039074112:stack/amplify-amplify-identity-broker-recronid-170044-authamplifyIdentityBrokerAuth-15OXJBUATXJ4N/fb3ec770-2782-11ec-a7ba-0ae128d1db7d was not successfully created: The following resource(s) failed to create: [MFALambdaInputs].
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED amplify-amplify-identity-broker-recronid-170044-authamplifyIdentityBrokerAuth-15OXJBUATXJ4N AWS::CloudFormation::Stack Thu Oct 07 2021 17:29:20 GMT+0200 (Midden-Europese zomertijd) The following resource(s) failed to create: [MFALambdaInputs].
⠇ Updating resources in the cloud. This may take a few minutes...

**Comment by sgarnovsky** [comment]
Found this solution recently while trying to make it's working:
https://issueexplorer.com/issue/aws-amplify/amplify-cli/8363

So the solution is only update MFALambdaRole declaration in this file: amplify/backend/auth/{APP_NAME}/{APP_NAME}-cloudformation-template.yml

So new added

Policies:
                - PolicyName: {resourceNameTruncated}_totp_pass_role_policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - "iam:PassRole"
                            Resource:
                                !If [
                                    ShouldNotCreateEnvResources,
                                    "arn:aws:iam:::role/{resourceNameTruncated}_totp_lambda_role",
                                    !Join [
                                        "",
                                        [
                                            "arn:aws:iam:::role/{resourceNameTruncated}_totp_lambda_role",
                                            "-",
                                            !Ref env,
                                        ],
                                    ],
                                ]
                _- PolicyName: {resourceNameTruncated}_sns_pass_role_policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - "iam:PassRole"
                            Resource: !GetAtt SNSRole.Arn_


There are other issues after this one:

- hosting bucket has to be updated to be unique:
\aws-amplify-identity-broker\amplify\backend\hosting\S3AndCloudFront\parameters.json
{
    "bucketName": "broker-{unique part}-hostingbucket"
}

- KMSMasterKeyID key should be set up to make build content published. 
"Resources": {
    "S3Bucket": {
      "Type": "AWS::S3::Bucket",
      "DeletionPolicy": "Retain",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "aws:kms",
                "KMSMasterKeyID": "arn:aws:kms:us-east-1:xxxxxxxxxxxxxx:key/{guid value}"
              }
            }
          ]
        },
It works when one active from Customer managed keys is used from this UI
https://console.aws.amazon.com/kms/home?region=us-east-X#/kms/keys


By the way, the project is builtt and looks published well:

npm results with:

<snip>
All resources are updated in the cloud

REST API endpoint: https://zzzzzzzzzzzzzz.execute-api.us-east-1.amazonaws.com/dev
Hosting endpoint: https://yyyyyyyyyy.cloudfront.net
Hosted UI Endpoint: https://amplifyidbrokerXXX-dev.auth.us-east-1.amazoncognito.com/
Test Your Hosted UI Endpoint: https://amplifyidbrokerXXX-dev.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=XXXXXXXXXXXXXXXXX&redirect_uri=https://injection.placeholder.amazon.com/
<snip>
Publish started for S3AndCloudFront
Uploaded files successfully.
Your app is published successfully.
https://yyyyyyyyyy.cloudfront.net

this endpoint (https://yyyyyyyyyy.cloudfront.net) generates this content (it just says the KMS key is incorrect?):
<Error>
<Code>KMS.UnrecognizedClientException</Code>
<Message>No account found for the given parameters</Message>
<RequestId>RKAZSQ3V1DKY9WFV</RequestId>
<HostId>LJaxq42Lhzrd5XRCWVs4v<snip>SmsU3l8i4IMWEGOo821s0G7+/v2o=</HostId>
</Error>


But it doesn't work as expected. I.e. only default Cognito hosted UI is displayed by this URL: https://amplifyidbrokerXXX-dev.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=XXXXXXXXXXXXXXXXX&redirect_uri=https://injection.placeholder.amazon.com/


AWS Amplify app doesn't look configured too (https://console.aws.amazon.com/amplify/home?region=us-east-X#/):
I.e. there are no "Rewrites and redirects" menu item available, so it is not possible to continue with "Deploying with the AWS Amplify console" doc part (https://github.com/awslabs/aws-amplify-identity-broker/blob/master/Documentation/UserDocumentation.md#deploying-with-the-aws-amplify-console)

So, I feel like doing something wrong too. 
Please let me know about things we are missing...

Having a fully customized Cognito Hosted UI with SSO support looks like a very powerful thing to use.

**Comment by martijn-veenstra** [comment]
Thanks for the replies. 
I did not get any further. Seems like this is just too good to be true :)

**Comment by sullix** [comment]
I had these issues too. And I'm reaching the same point.

```
<Error>
  <Code>KMS.UnrecognizedClientException</Code>
  <Message>No account found for the given parameters</Message>
  <RequestId>DPE83873N7JJM0JH</RequestId>. 
  <HostId>OXRwoZYKbsfBlElUHvn4dEnN9TAfidsNQ9CFDA5CvIB82tiagAw1iqPrX9wJBBrDyAU596yHUT4=</HostId>
</Error>
```

I am therefore unable to deploy this so useful project.
However, everything seems to be configured as expected in the amplify directory.

**Comment by maekawataiki** [comment]
We published the fix for this.
Please let us know if you're still stuck.
