### ISSUE TITLE
Make the broker 100% OIDC standard

### ISSUE THREAD

**Issue by xavierraffin** [awslabs/aws-amplify-identity-broker#27]
As mention in the [documentation](https://github.com/awslabs/aws-amplify-identity-broker/blob/master/Documentation/UserDocumentation.md#difference-with-the-oidc-standard), there is one small exception to the standard that the broker makes:

_/oauth2/userinfo: The Oauth2 standard stipulate that the UserInfo endpoint MUST accept Access Tokens as OAuth 2.0 Bearer Token Usage. The broker do not use that but instead is expecting the token to be provided inside a HTTP header named access_token. If this is a bloker for you, you can use the UserInfo endpoint that Amazon Cognito expose directly._

This exception may be possible to fix by moving the /oauth2/userinfo from proxy lambda integration to proxy and therefore access the authentication headers within the lambda.

In your PR please add change to the doc (and on this page that link to the section above: https://github.com/awslabs/aws-amplify-identity-broker/blob/master/Documentation/ClientDeveloperDocumentation.md)

**Comment by clfsoft** [comment]
Authorization header is not forwarded by cloudfront 
https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-authorization-header/
apigateway did forward Authorization header in case not setting authorize by aws_iam
