### ISSUE TITLE
When Cognito App Client with secret is used then it is having issue with Broker Login

### ISSUE THREAD

**Issue by Vijay882** [awslabs/aws-amplify-identity-broker#373]
Error message in Login screen.
Client AppClientId(ex: 4k4kk68josebslhdsfsdfsfsd) is configured for secret but secret was not received.

Reproduce: Create App Client which also has **secret** and use it in config-override.js of aws-amplify-identity-broker-client application for testing login. It shows above error message in broker login screen.

**Comment by maekawataiki** [comment]
Hi @Vijay882 👋
Thanks for opening the issue.

Could you check your Cognito Client is configured __without__ client secret?

You can delete the Cognito client and recreate it. Ensure `Generate client secret` is unchecked.

We have it on the doc, but it is in long text and not emphasized. 
I'll mark it as documentation improvement.

https://github.com/awslabs/aws-amplify-identity-broker/blob/master/Documentation/UserDocumentation.md#register-a-client

**Comment by Vijay882** [comment]
> Hi @Vijay882 👋 Thanks for opening the issue.
> 
> Could you check your Cognito Client is configured **without** client secret?
> 
> You can delete the Cognito client and recreate it. Ensure `Generate client secret` is unchecked.
> 
> We have it on the doc, but it is in long text and not emphasized. I'll mark it as documentation improvement.
> 
> https://github.com/awslabs/aws-amplify-identity-broker/blob/master/Documentation/UserDocumentation.md#register-a-client

I saw it in the documentation but we initially had an requirement to have an App Client with Secret. Any way it's not an issue for us now.
