### ISSUE TITLE
Access Token returning incorrect scope(aws.cognito.signin.user.admin) 

### ISSUE THREAD

**Issue by Vijay882** [awslabs/aws-amplify-identity-broker#376]
My Cognito App Client has openid scope selected in the cognito user pool. Returned Access token always contains "aws.cognito.signin.user.admin" scope instead of openid which we selected. Please let me know on how to get the right scopes which are selected in the user pool/app client settings.

Example:
{
  "sub": "TEST",,
  "iss": "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TEST",
  "client_id": "TEST",
  "origin_jti": "TEST",
  "event_id": "c79604fe-b3a8-406c-8b2d-5524a7e6b038",
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
  "auth_time": 1667402819,
  "exp": 1667406419,
  "iat": 1667402819,
  "jti": "TEST",,
  "username": "TEST"
}

**Comment by maekawataiki** [comment]
Hi @Vijay882 👋
Thanks for opening the issue.

What would you like to do with the openid scope?

Apparently it is not possible to get scope outside of Hosted UI.

https://github.com/aws-amplify/amplify-js/issues/3732

If you are trying to perform authorization, you may use `cognito:group` as workaround.

**Comment by Vijay882** [comment]
Thanks for your response.
