### ISSUE TITLE
Existing cognito user pool

### ISSUE THREAD

**Issue by Vijay882** [awslabs/aws-amplify-identity-broker#382]
Will this solution work with existing cognito user pool instead of creating new pool. I saw documentation for migrating users from one pool to other but we have thousands of users and we are not interested to take migration path.

**Comment by maekawataiki** [comment]
Hi @Vijay882

Yes, you can use existing Cognito User Pool.

Here is the steps I tested to deploy this application with existing Cognito User Pool

1. Deploy AmplifyIdentityBroker without Cognito
    1. Create Cognito Client in existing Cognito
    2. Delete `amplify/team-provider-info.json`
    3. Update `amplify/backend/backend-config.json`
        1. Add property `"serviceType": "imported"` to `amplifyIdentityBrokerAuth`
    4. Delete `amplify/backend/auth/amplifyIdentityBrokerAuth/amplifyIdentityBrokerAuth-cloudformation-template.yml`
    5. Run `amplify init`
    6. Run `amplify push`
2. Add required setting to existing Cognito following settings in `amplify/backend/auth/amplifyIdentityBrokerAuth/amplifyIdentityBrokerAuth-cloudformation-template.yml` (**This step may affect existing application. Test it carefully with development environment**)
    1. Add Custom Attributes (Boolean attributes cannot be created with console, so use SDK or CLI)
    2. Associate Lambda Triggers
    3. Check other settings are set correctly (i.e. MFA, CognitoDomain, callback URLs, ...)
