### ISSUE TITLE
Amplify publish is throwing errors

### ISSUE THREAD

**Issue by rsercano** [awslabs/aws-amplify-identity-broker#458]
Hello, 

Since hosted UI and custom UI have drawbacks on their own, this project seems a way to go for us. But as a simple trial to publish resulted with below errors:

`Name: LambdaFunction (AWS::Lambda::Function), Event Type: create, Reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 9b4f9bc2-0f0d-482c-b506-8b24366b68ad)" (RequestToken: 3ea1c5c1-890c-250e-4c02-513ff1e6a5fe, HandlerErrorCode: InvalidRequest)`

Also can you please confirm how up to date and secure to use this project on production?

**Comment by alphan-nthu** [comment]
This is how I fixed the errors.
Bump the runtime to nodejs14.x.
```
-        "Runtime": "nodejs12.x",
+        "Runtime": "nodejs14.x",
```

There are 14 files needed to apply the change.
 amplify/backend/function/
-amplifyIdentityBrokerAccountConfirmation/amplifyIdentityBrokerAccountConfirmation-cloudformation-template.json | 2 +-
-amplifyIdentityBrokerAuthorize/amplifyIdentityBrokerAuthorize-cloudformation-template.json                     | 2 +-
-amplifyIdentityBrokerClients/amplifyIdentityBrokerClients-cloudformation-template.json                         | 2 +-
-amplifyIdentityBrokerCreateAuthChallenge/amplifyIdentityBrokerCreateAuthChallenge-cloudformation-template.json | 2 +-
-amplifyIdentityBrokerCustomMessage/amplifyIdentityBrokerCustomMessage-cloudformation-template.json             | 2 +-
-amplifyIdentityBrokerDefineAuthChallenge/amplifyIdentityBrokerDefineAuthChallenge-cloudformation-template.json | 2 +-
-amplifyIdentityBrokerExposeJWKS/amplifyIdentityBrokerExposeJWKS-cloudformation-template.json                   | 2 +-
-amplifyIdentityBrokerMigration/amplifyIdentityBrokerMigration-cloudformation-template.json                     | 2 +-
-amplifyIdentityBrokerPostDeployment/amplifyIdentityBrokerPostDeployment-cloudformation-template.json           | 2 +-
-amplifyIdentityBrokerStorage/amplifyIdentityBrokerStorage-cloudformation-template.json                         | 2 +-
-amplifyIdentityBrokerToken/amplifyIdentityBrokerToken-cloudformation-template.json                             | 2 +-
-amplifyIdentityBrokerUserInfo/amplifyIdentityBrokerUserInfo-cloudformation-template.json                       | 2 +-
-amplifyIdentityBrokerVerifyAuthChallenge/amplifyIdentityBrokerVerifyAuthChallenge-cloudformation-template.json | 2 +-
-amplifyIdentityBrokerVerifyClient/amplifyIdentityBrokerVerifyClient-cloudformation-template.json               | 2 +-

**Comment by maekawataiki** [comment]
nodejs version is updated to 16.x. amplify publish should work.
Feel free to reopen if the issue persists.
