### ISSUE TITLE
The Reset Password page in the sample app asks for an email address three times

### ISSUE THREAD

**Issue by cbp123** [awslabs/aws-amplify-identity-broker#84]
See the attached screenshot
 ![image](https://user-images.githubusercontent.com/1452529/111070503-29b65a00-8526-11eb-8150-eb5e5f357b12.png)

**Comment by nbaeumer** [comment]
Thanks! Will check this out.

**Comment by maekawataiki** [comment]
This issue is fixed in @aws-amplify/ui-react@1.2.8 and should be fixed by updating the package.
https://github.com/aws-amplify/amplify-js/issues/8629
https://github.com/aws-amplify/amplify-js/compare/@aws-amplify/ui-react@1.2.7...@aws-amplify/ui-react@1.2.8
